# This is a basic workflow to help you get started with Actions

name: Windows

on:
  workflow_dispatch:
  release:
    types: [published]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1

    env:
      PROJECT_NAME: "rfxgen"
      PROJECT_VERSION: "2.5"
      RELEASE_PATH: ${{ env.PROJECT_NAME }}_v${{ env.PROJECT_VERSION }}_win_x64
      VS_RELEASE_PATH: build

    steps:
    - name: Checkout this repo
      uses: actions/checkout@master
      
    - name: Checkout raylib repo
      uses: actions/checkout@v2
      with:
        repository: raysan5/raylib
        path: raylib
    
    - name: Setup Release Version
      run: |
        echo "RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ env.PROJECT_VERSION }}_win_x64" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'

    # NOTE: Visual Studio project build configuration already defines all required directories where project is generated
    # $(SolutionDir)\build\$(ProjectName)\bin\$(Platform)\$(Configuration)\
    # By default for this build: rfxgen\project\VS2022\build\rfxgen\bin\x64\Release\
    - name: Setup Environment
      run: | 
        dir
        mkdir build
        cd build
        mkdir ${{ env.RELEASE_PATH }}
        cd ..
        echo "VS_RELEASE_PATH=project\VS2022\build\${{ env.PROJECT_NAME }}\x64\Release" >> $GITHUB_ENV
      shell: cmd

    # Setup MSBuild.exe path if required
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1

    - name: Build Solution
      run: |
        cd projects/VS2022
        msbuild.exe ${{ env.PROJECT_NAME }}.sln /target:${{ env.PROJECT_NAME }} /property:Configuration=Release /property:Platform=x64
        cd ../..
      shell: cmd

    - name: Generate Artifacts
      run: |
        copy /Y ${{ VS_RELEASE_PATH }}\${{ env.PROJECT_NAME }}.exe .\build\${{ env.RELEASE_PATH }}\${{ env.PROJECT_NAME }}.exe
        copy /Y .\README.md .\build\${{ env.RELEASE_PATH }}\README.md
        copy /Y .\LICENSE .\build\${{ env.RELEASE_PATH }}\LICENSE
        cd build
        7z a ./${{ env.RELEASE_PATH }}.zip ./${{ env.RELEASE_PATH }}
        dir
      shell: cmd

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.RELEASE_NAME }}.zip
        path: ./build/${{ env.RELEASE_NAME }}.zip
        
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./build/${{ env.RELEASE_NAME }}.zip
        asset_name: ${{ env.RELEASE_NAME }}.zip
        asset_content_type: application/zip
      if: github.event_name == 'release' && github.event.action == 'published'
